server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: gongda-circle

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gongda_circle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: gongda_circle  # 修改为你在宝塔面板创建的数据库用户名
    password: E8zzm53GD7GabsRw   # 修改为你的数据库密码
    
    # Druid连接池配置
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat,wall,slf4j
      # 配置监控页面
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456  # 修改为你的Druid监控页面密码
        allow: 127.0.0.1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  # Redis配置 (如果你的服务器有Redis)
  redis:
    host: localhost
    port: 6379
    password:  # 如果有密码，请设置
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 开启Mybatis二级缓存，默认为 true
    cache-enabled: false
    # 日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # mapper文件位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# 日志配置
logging:
  level:
    com.gongda.gongdacircle: info
    org.springframework.security: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
  file:
    name: /www/wwwroot/gongdacircle/logs/gongda-circle.log  # 修改为你的宝塔面板网站目录
    max-size: 10MB
    max-history: 30

# JWT配置
jwt:
  secret: gongdacircle2024securitykeyatleast32byteslongprod  # 生产环境使用更强的密钥
  expiration: 86400000  # 24小时，单位：毫秒

# 文件上传配置
file:
  upload:
    path: /www/wwwroot/gongdacircle/uploads/  # 修改为你的宝塔面板网站上传目录
    max-size: 10MB 